# Generated by Django 3.1.6 on 2021-02-08 20:12

from django.db import migrations


def some_forward_action(apps, schema_editor):
    Product = apps.get_model('myapp', 'Product')
    Product.objects.create(name='TV', description='For a Wall', price=1000, quantity=3, available=True)
    Product.objects.create(name='Phone', description='For them ', price=800, quantity=5, available=True)


class Migration(migrations.Migration):
    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(some_forward_action, lambda x, y: None)
    ]
